API_ID: 9998484
API_HASH: 86dbbc3288bbcf9fe1753e1c4ae1f517
BOT_TOKEN: 5077201853:AAEcwtNbeeEyjmhQ4SeYE3GFeLO-ltNHFiw


MONGO_URL: mongodb+srv://afiqsam:afiqsam@cluster0.0wb1c.mongodb.net/afiqsam?retryWrites=true&w=majority
REDIS_URI:
REDIS_PORT:
REDIS_PASS:

SESSION_API_ID: 
SESSION_API_HASH: 
SESSION_STRING: 

ADMINS: 
  - 1317173146

OWNER: 1317173146

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: roldexversechats 
# LOG_CHAT: 
LOG_CHAT: 



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

